name: 🚀 Feature Request
description: Suggest an idea, feature, or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an idea. It helps make uustupid better.
  - type: textarea
    attributes:
      label: What is the feature you are proposing?
      description: A clear description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is this feature useful?
      description: Explain the use case or problem this feature solves.
